language: cpp

# cache:
#     directories:
#         - build
#         - bin
#         - share


beforce_cache:
    - cd build && rm -rf -- !(_deps)

env:
    - BOOST_ROOT=/usr/local Eigen3_DIR=build/_deps/eigen3-build

before_install:
    - if [[ ! -e bin/cmake || ! -d share/cmake-3.19 ]];
          then wget https://github.com/Kitware/CMake/releases/download/v3.19.0-rc3/cmake-3.19.0-rc3-Linux-x86_64.sh;
          chmod +x cmake-3.*.sh;
          ./cmake-3.*.sh --skip-license --exclude-subdir;
      fi

install:
    - sudo bin/cmake -B build . -DCMAKE_BUILD_TYPE=RELEASE
    - sudo make -C build -j

script: sudo make -C build test
