dist: focal

language: python

python:
    - "3.6"

before_install:
    - sudo apt-get install libgtest-dev

install:
    - pip3 install conan
    - conan profile new default --detect
    - conan profile update settings.compiler.libcxx=libstdc++11 default
    - mkdir build && cd build
    - conan install .. -s build_type=Release
    - cmake .. -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release
    - make -j

script:
    - make test
